### ISSUE TITLE
MacBook Pro 打开后会闪退，但顶部有应用的图标，点击之后只有浮现退出按钮，无其他可操作的地方

### ISSUE THREAD

**Issue by 3scarecrow** [Synaptrix/ChatGPT-Desktop#126]

**Comment by bilibili-ayang** [comment]
感谢反馈，提供你的一下你的电脑版本！

**Comment by LiMengSir** [comment]
同上问题，电脑版本：MacBook Pro M1Pro macOS Monterey 12.0

**Comment by 3scarecrow** [comment]
> 感谢反馈，提供你的一下你的电脑版本！

MacBook Pro (13-inch, M1, 2020)款，系统版本是 12.0.1，大佬看看能不能解决一下

**Comment by bilibili-ayang** [comment]
你们是第一次下载还是旧版本升级？ @3scarecrow @LiMengSir

**Comment by 3scarecrow** [comment]
> 你们是第一次下载还是旧版本升级？ @3scarecrow @LiMengSir

第一次下载安装的时候遇到的

**Comment by bilibili-ayang** [comment]
> > 你们是第一次下载还是旧版本升级？ @3scarecrow @LiMengSir
> 
> 第一次下载安装的时候遇到的

这就难受了，得统一在 debug 模式排查问题！

**Comment by LiMengSir** [comment]
我也是第一次安装

**Comment by weiguang01** [comment]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) 同一个问题

**Comment by bilibili-ayang** [comment]
@3scarecrow @LiMengSir @weiguang01 看到先加到 dc 聊天群，我们做了一个向下兼容的版本，可以帮忙测试一波！

**Comment by orangelckc** [comment]
1.0 正式版已修复该问题，麻烦各位更新最新版，如果还有问题，可以回来反馈！
@3scarecrow @LiMengSir @weiguang01

**Comment by taliove** [comment]
README.md 里面下载的 M芯片版本，打开时已损坏，无法打开。

**Comment by bilibili-ayang** [comment]
感谢反馈，请参考文档 常见问题 2

**Comment by bilibili-ayang** [comment]
> README.md 里面下载的 M芯片版本，打开时已损坏，无法打开。

感谢反馈，请参考文档 常见问题 2

**Comment by taliove** [comment]
> > README.md 里面下载的 M芯片版本，打开时已损坏，无法打开。
> 
> 感谢反馈，请参考文档 常见问题 2

感谢，我已通过下载Release里面的ChatGPT-Desktop.app.tar.gz解决可以使用。
