### ISSUE TITLE
Windows 安装包，提示有毒！MacOS 安装包，提示 app 已损坏，无法打开。

### ISSUE THREAD

**Issue by alindas** [Synaptrix/ChatGPT-Desktop#141]
你们会这样提示吗

**Comment by ink0101** [comment]
yes 会被系统杀毒软件干掉

**Comment by bilibili-ayang** [comment]
感谢反馈，软件是通过 tauri 提供的 ci 打包的，完全可以放心使用，报错应该是误报，不影响正常使用的，我们在正在找解决方案！

**Comment by bilibili-ayang** [comment]
MacOS 问题以及解决方案：

<img width="290" alt="problem-1" src="https://user-images.githubusercontent.com/75017711/229003186-0a5a5940-fda9-459b-af6d-bcdcfedd370b.png">

参考 huazai 大佬的[解决办法](https://zhuanlan.zhihu.com/p/135948430)

**Comment by bilibili-ayang** [comment]
Windows 安装包是通过 tauri 提供的 ci 打包的，完全可以放心使用，报错应该是软件没签名导致的误报！

Windows 问题已经解决方案：

 1. 下载报错：关闭防火墙即可下载成功！
 2. 安装以及启动报错：将软件放到白名单即可！

**Comment by soup-Lee** [comment]
软件代码全部开源，可放心使用，报毒的错误正在修复，无法下载的小伙伴们可以根据下面的步骤操作：
<img width="180" alt="7c450d7e5aa53a7b22dec607a83b488" src="https://user-images.githubusercontent.com/79054161/229034672-a2428fcc-bac4-4ede-96c4-115de4cfe0e4.png">
<img width="180" alt="0443e8dfd7048155a0442d9def36862" src="https://user-images.githubusercontent.com/79054161/229034689-5c0e9512-fcd9-4586-9c88-b0753a895aaa.png">
<img width="180" alt="0443e8dfd7048155a0442d9def36862" src="https://user-images.githubusercontent.com/79054161/229034803-860c3700-25aa-441e-ad9f-e1b796b39e46.png">

如果仍然提醒：无法下载-检测到病毒
<img width="180" alt="b7d571a847571d933642d8880228598" src="https://user-images.githubusercontent.com/79054161/229034960-2a219b75-bb5e-45cb-bf72-004518c821bd.png">

可以按照下面的步骤操作：
<img width="768" alt="7895285938e96238269912cf59a2025" src="https://user-images.githubusercontent.com/79054161/229034995-69b7a66c-a143-4379-8b59-4818f65dc171.png">
<img width="657" alt="d845a925556d2ce722938b831ec01b4" src="https://user-images.githubusercontent.com/79054161/229035014-66575c59-5011-4afa-a726-bd377c9c5e47.png">
<img width="486" alt="ada0598324a434ffce63c06561c5e91" src="https://user-images.githubusercontent.com/79054161/229035107-5aa55f56-7cb7-4585-bb6b-fa303e368b2f.png">

关闭此处的实时防护，然后重新点击下载msi文件

**Comment by PlutoOfCharon** [comment]
最新版本安装无问题

**Comment by orangelckc** [comment]
@PlutoOfCharon 感谢反馈！

**Comment by orangelckc** [comment]
![image](https://user-images.githubusercontent.com/48410934/229338595-cf1cf323-622f-4299-bc65-92f6ba3c2102.png)

已通过微软的审查，请放心使用1.0.0的版本
这个issue我就先关闭了 😄
