### ISSUE TITLE
希望程序窗体大小可以调节等

### ISSUE THREAD

**Issue by gegedanongchang** [Synaptrix/ChatGPT-Desktop#147]
核心功能非常强，用户体验方面希望可以允许我提出以下两点需求：
①
![image](https://user-images.githubusercontent.com/86853743/229013894-e7affa33-60d5-4a62-837b-aab8b8c1c007.png)
↑希望整个红框区域都是可以拖动的。

②
希望窗体大小可以调节，我想要更小的窗体。

软件以及系统信息如下：{"appName":"ChatGPT-Desktop","appVersion":"1.0.0","tauriVersion":"1.2.4","platform":"win32","os":"Windows_NT","osVersion":"10.0.19044","arch":"x86_64","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54"}

**Comment by soup-Lee** [comment]
非常感谢您的建议，这两项功能对于提升用户体验的帮助无疑是非常大的，我们会在版本稳定后进行添加，敬请期待！

**Comment by bilibili-ayang** [comment]
窗口已加入根据屏幕大小自动缩放至合适的尺寸！
