### ISSUE TITLE
Linux 中几个启动错误，涉及 Release v1.0.0 版本,

### ISSUE THREAD

**Issue by zinface** [Synaptrix/ChatGPT-Desktop#148]
- Linux Deepin 20.8 中启动错误，要求的 GLIBC_2.29 not found ，这是因为 libc6 版本低
    ![image](https://user-images.githubusercontent.com/46606043/229016104-0b1d48b3-a651-40cb-89da-483edd3bdfd6.png)

- Linux Ubuntu 22.04 中启动错误，要求 libssl.so.1.1，这是因为源中只有 libssl3，并没有 libssl1.1 版本低
   ![image](https://user-images.githubusercontent.com/46606043/229017919-7f26713b-2501-47ce-bcb5-dd4301d9a2f0.png)

- 补充
    1. Ubuntu 22.04 中使用 Appimage 并安装 libfuse2 可正常运行

**Comment by orangelckc** [comment]
@zinface 目前我们团队没有成员可以帮忙测试Linux的适配性，如果你有意愿加入我们，可以加入Discord社区，帮助我们改进这个问题

**Comment by zinface** [comment]
![image](https://user-images.githubusercontent.com/46606043/229155370-a0f562e9-274a-4d7e-9442-875748a863c3.png)
