### ISSUE TITLE
export picture

### ISSUE THREAD

**Issue by Zeng-HB157** [Synaptrix/ChatGPT-Desktop#154]
I dont know how to export the picture to my computer. It shows export successfully，but I dont know where is the picture.

**Comment by bilibili-ayang** [comment]
What is the version you are downloading? We've added the ability to export files to open folders and select files in v1.0.0! If it is v1.0.0, please provide the information copied in the software!

**Comment by orangelckc** [comment]
> 

Please download the images by hovering over them and clicking the download button. The images will be downloaded to your default download folder, unless you have changed its location. If you have any trouble downloading the images, please let us know.

**Comment by orangelckc** [comment]
@Zeng-HB157 
If you are a native English speaker and would like to join us, you are more than welcome. We are currently planning to add multi-language support. And you maybe contribute on it.

**Comment by Zeng-HB157** [comment]
Hi
I am interested in your group！ But it's a pity that my native language is Chinese.&nbsp; Please do contact me if I can be of help.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 31, 2023 17:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChatGPT-Desktop/ChatGPT-Desktop] export picture (Issue #154)




 
@Zeng-HB157
 If you are a native English speaker and would like to join us, you are more than welcome. We are currently planning to add multi-language support. And you maybe contribute on it.

**Comment by Zeng-HB157** [comment]
我很有兴趣呀。不知道自己可以做什么呢

--------------原始邮件--------------
发件人："ayang ***@***.***&gt;;
发送时间：2023年4月3日(星期一) 下午4:05
收件人："Synaptrix/ChatGPT-Desktop" ***@***.***&gt;;
抄送："曾焕彬 ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [Synaptrix/ChatGPT-Desktop] export picture (Issue #154)
-----------------------------------

 

 
@Zeng-HB157 要不要来支持国际化？

**Comment by bilibili-ayang** [comment]
@Zeng-HB157 可以先加入到 [Discord](https://discord.gg/jg4waryfA6)，然后我们再去落实！
