### ISSUE TITLE
Ubuntu 20 快捷键无法唤起 & 状态栏左键无法唤起(需要增加一个`显示`菜单)

### ISSUE THREAD

**Issue by orangelckc** [Synaptrix/ChatGPT-Desktop#155]
Ubuntu 20 快捷键无法唤起 & 状态栏左键无法唤起(需要增加一个`显示`菜单)

_Originally posted by @pkptzx in https://github.com/ChatGPT-Desktop/ChatGPT-Desktop/issues/148#issuecomment-1491704406_

**Comment by bilibili-ayang** [comment]
#158
