### ISSUE TITLE
文字模式可以正常使用，图像模式没反应。或是需要使用我没看到的教程？

### ISSUE THREAD

**Issue by LiSir7** [Synaptrix/ChatGPT-Desktop#160]

**Comment by LiSir7** [comment]
[](url)
![QQ截图20230401200224](https://user-images.githubusercontent.com/52618086/229287466-1e4a919d-ab60-48af-9215-f350b40f616d.png)
如图，此时为图像模式

**Comment by bilibili-ayang** [comment]
感谢反馈，你可以多尝试几次，和文字模式使用方法一样！我们这边测试没问题！
