### ISSUE TITLE
请求的 key 超出限制

### ISSUE THREAD

**Issue by Cuibaby** [Synaptrix/ChatGPT-Desktop#164]
请问配置完API KEY后显示”请求的 key 超出限制“是什么原因？

**Comment by orangelckc** [comment]
建议去问openai的客服，非软件问题，抱歉，帮不到你！

**Comment by zengleyi** [comment]
我也有这个问题，请问你最后是怎么解决的？

**Comment by orangelckc** [comment]
该提示对应接口返回代码`429`，具体情况需要根据自己的账户进行核查！
![image](https://user-images.githubusercontent.com/48410934/229337354-022ad0f0-8121-425d-85a3-df9ae9a2af01.png)

**Comment by xupengmamba** [comment]
同问，不好解决呢，有没有大佬解决过的！！！

**Comment by BinGo1010** [comment]
![image](https://github.com/Synaptrix/ChatGPT-Desktop/assets/75125009/c7058079-0961-48b7-83a3-6a376f84191f)
也许是免费额度到期或用完了，解决方法就是充钱了吧。

**Comment by BinGo1010** [comment]
![image](https://github.com/Synaptrix/ChatGPT-Desktop/assets/75125009/fb58bb43-70a0-461b-a501-7e263408cc3f)
我尝试绑定银行卡，但是我的国内银行卡不支持。。。目前，我只能凑合点开网页版chat-gpt用，调用api到后面应该都会遇到这个问题吧，希望大佬对萌新指点一二，求解决方法。。。
