### ISSUE TITLE
Support for internationalization (i18n)

### ISSUE THREAD

**Issue by davidramos-om** [Synaptrix/ChatGPT-Desktop#166]
Is i18n down the line? I can help out on this.

Could be i18n or any of your preference.

**Comment by orangelckc** [comment]
Thank you for your interest in our project. Internationalization support is already on our development roadmap, and we welcome your help in pushing forward this feature even faster. 
- Are you familiar enough with Chinese to directly translate it into English? 
- Do you need us to extract the text variables first?

I think you may begin by translating the README document.

**Comment by davidramos-om** [comment]
Hi.

Tbh, I'm not familiar with Chinese. I intended to use translating apps and ask around some Chinese friends so they could help me accurately understand the texts.

Not needed to extract text, I'll look into the code and get the labels.

Let's move to discord chat.

**Comment by orangelckc** [comment]
> Hi.
> 
> Tbh, I'm not familiar with Chinese. I intended to use translating apps and ask around some Chinese friends so they could help me accurately understand the texts.
> 
> Not needed to extract text, I'll look into the code and get the labels.
> 
> Let's move to discord chat.

Welcome to join us! 

You can use ChatGPT for translation and use the software itself during development. 
It is really a very cool experience.
