### ISSUE TITLE
希望支持一下账号密码登陆而不是token

### ISSUE THREAD

**Issue by 1049731887** [Synaptrix/ChatGPT-Desktop#167]
参照ChatGPT for Google浏览器插件。使用token会耗费余额，而使用账号密码完全免费

**Comment by orangelckc** [comment]
目前不考虑这种方式，chrome插件应该是通过直接使用你登陆后保存在浏览器的cookie来进行调用的，这与我们使用api的方式调用接口不同，理论上使用api会更稳定。

而且，作为开发者，我个人建议您不要在任何第三方软件或插件填入自己的帐号密码，这有很高的安全风险，望参考！
