### ISSUE TITLE
支持选择所使用的模型

### ISSUE THREAD

**Issue by ArcticLampyrid** [Synaptrix/ChatGPT-Desktop#171]

**Comment by orangelckc** [comment]
目前软件使用最新`GPT3.5-turbo-0301`模型，这是目前使用效果与收费最平衡的模型，同时支持文字+图片模式，我们的功能面向的并非需要微调模型或其他专业领域模型的专业用户，很抱歉！

希望您可以找到自己预期的软件，当然如果有能力，欢迎基于我们的项目进行二开，做出满足自己需求的软件！

Good day！

**Comment by ArcticLampyrid** [comment]
至少应该支持选择使用GPT-4模型，GPT-3.5在很多场合还是不太够用的

**Comment by macvip** [comment]
尝试将源码中的`OPEN_AI_MODEL`的值改为`gpt-4`，重新编译后，发现文本模式和图片模式一切正常。
还是希望作者能考虑一下加入选择模型的功能，谢谢🙏
