### ISSUE TITLE
希望在不删除历史记录的情况下可以切换和新增角色

### ISSUE THREAD

**Issue by jinshengcui** [Synaptrix/ChatGPT-Desktop#174]
首先非常感谢大佬的贡献，使用起来非常好！
有一个小小的建议，就是单个角色对话之后，我想切换到另外一个角色，就不得不把之前的角色对话记录删除掉才能使用添加和切换角色功能。希望在不删除历史记录的情况下可以切换和新增角色。感恩~！

**Comment by jinshengcui** [comment]
然后希望可以自定义上传图片生成头像，感恩！

**Comment by bilibili-ayang** [comment]
> 然后希望可以自定义上传图片生成头像，感恩！

#119
