### ISSUE TITLE
经常会出现 请求出错 需要再重新发下才行，这个是个人网络问题么还是？

### ISSUE THREAD

**Issue by lyx-v** [Synaptrix/ChatGPT-Desktop#179]

**Comment by lyx-v** [comment]
![image](https://user-images.githubusercontent.com/94749710/229681447-0efee55d-752b-483f-98a2-4e9671b944b2.png)

**Comment by bilibili-ayang** [comment]
感谢反馈，这是网络问题，需要保证有稳定的网络，或者使用我们提供的转发服务器！
