### ISSUE TITLE
代理网络问题

### ISSUE THREAD

**Issue by chingwl** [Synaptrix/ChatGPT-Desktop#180]
# 代理网络问题
我用nginx配置了一个自己的域名反向代理到https://api.openai.com/
通过自己的域名可以请求正常返回结果
<img width="380" alt="image" src="https://user-images.githubusercontent.com/34591566/229688783-00382c07-63a9-4601-b078-2e1fc2aa4289.png">
把自己的域名填到代理地址后使用提示网络有问题，前提key可以正常使用：
![image](https://user-images.githubusercontent.com/34591566/229688520-d5887c59-76ff-48a1-9471-3d9710617afb.png)
![image](https://user-images.githubusercontent.com/34591566/229688533-cd503666-1da9-4945-9cfa-d19baf08dc65.png)

**Comment by LongLiveY96** [comment]
需要/api结尾

**Comment by wmbin** [comment]
是否可以支持socks或者http的方式呢
本机代理但是没有设置为系统级

**Comment by chingwl** [comment]
> 需要/api结尾

调整为/api结尾后，问题并没有解决：

这是软件截图：
<img width="800" alt="image" src="https://user-images.githubusercontent.com/34591566/229723992-9a43bd69-e7c7-47f2-984e-6448c544251e.png">
这是通过浏览器访问：
<img width="637" alt="image" src="https://user-images.githubusercontent.com/34591566/229724118-64843122-513e-4e52-b9a4-696fdaa886a9.png">
这是我的nginx配置：
<img width="479" alt="image" src="https://user-images.githubusercontent.com/34591566/229724285-98898fb1-b7e9-4f15-b40e-33c3d5b896d1.png">

**Comment by chingwl** [comment]
> 是否可以支持socks或者http的方式呢 本机代理但是没有设置为系统级

我配置的是nginx的反向代理，不是你说的魔法代理。

没太理解“本机代理但是没有设置为系统级”，这个和设置系统级没关系吧。

我本机有魔法代理，已设置系统级别代理，使用本软件还是会出现网络问题。

**Comment by bilibili-ayang** [comment]
感谢反馈，目前并没有做本地代理的适配，因为每个人使用代理的软件以及设置都不相同，很难做到统一，为了更好的使用体验，建议使用我们提供的代理解决方案，会更稳定可靠

**Comment by orangelckc** [comment]
> > 是否可以支持socks或者http的方式呢 本机代理但是没有设置为系统级
> 
> 我配置的是nginx的反向代理，不是你说的魔法代理。
> 
> 没太理解“本机代理但是没有设置为系统级”，这个和设置系统级没关系吧。
> 
> 我本机有魔法代理，已设置系统级别代理，使用本软件还是会出现网络问题。

系统代理：
- 需要打开全局代理，或者单独配置允许某个特定软件走代理流量
- 不同代理软件的设置不同，甚至有的并不支持独立设置，这也是我们不选择这个方案的原因
- 最近OPENAI大批量封号，不建议使用不稳定的代理，有被封号的风险

你的Nginx代理：
- 尝试改成https，并且创建SSL证书，http连接在tauri中是被禁止的
- 在软件中填入你自己的代理服务器地址，并在服务器端进行调试
- 有可能使用这种方案会丢失流失输出的特性，并且因为较长回答导致超时失败，需要你自己去做适配

如果你成功了，可以写一个教程，方便社区和你有同样需求的人。
