### ISSUE TITLE
首先感谢开源，软件核心功能非常好用，一点小建议，希望采纳

### ISSUE THREAD

**Issue by Imhemers** [Synaptrix/ChatGPT-Desktop#184]
首先感谢开源，软件核心功能非常好用

在以上前提下，想提一点小建议
1：支持换头像(包括AI的头像)
2：希望支持隐藏每条消息上方的时间显示，时间是不相关信息，有部分用户(比方说我)不关心时间，去掉时间展示后可以使信息更加专注，从产品方向考虑，可能有部分用户希望展示时间，可以考虑在设置弄一个开关是否显示时间

希望采纳【抱拳】

**Comment by bilibili-ayang** [comment]
感谢支持😁

1. #119 
2. 此建议已采纳，下个版本将会加入开关来控制！
