### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by Imhemers** [Synaptrix/ChatGPT-Desktop#195]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/18650947/230324844-a12d9d0b-ebef-4644-9143-9fc3e06770a1.png">

这版的窗口比之前还小了一点，导致样式有一丢丢问题（小问题，功能不受影响）
回到问题本质：窗口根据设备宽度来自适应可能不是一个好方案，建议是否支持窗口调节尺寸（当然看你们实现成本）

软件以及系统信息如下：{"appName":"ChatGPT-Desktop","appVersion":"1.0.1","tauriVersion":"1.2.4","platform":"darwin","os":"Darwin","osVersion":"12.4.0","arch":"x86_64","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"}

**Comment by bilibili-ayang** [comment]
感谢反馈，没有小屏幕确实没测试到这个问题，这个也好解决，固定最小窗口尺寸就好啦！

**Comment by DongHuiTiao** [comment]
感谢反馈，这个问题我们还在探讨中，也希望获得更多用户对该需求的反馈，为我们的决策提供参考。

可以在 #198 中参与投票

感谢您的使用和支持
