### ISSUE TITLE
请求出错

### ISSUE THREAD

**Issue by nihaozyj** [Synaptrix/ChatGPT-Desktop#197]
![image](https://user-images.githubusercontent.com/58590015/230566955-2861f306-0d44-4f43-a1ba-5921007473c7.png)
软件以及系统信息如下：{"appName":"ChatGPT-Desktop","appVersion":"1.0.1","tauriVersion":"1.2.4","platform":"win32","os":"Windows_NT","osVersion":"10.0.22621","arch":"x86_64","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62"}

试了其他软件，不会出现这个问题

**Comment by DongHuiTiao** [comment]
感谢反馈。

1. 检查 设置 / 模型 / OpenAI API KEY 是否填写正确
2. 检查 网络 是否支持 访问
3. 若网络不支持，检查是否在 设置 / 通用 中启动了 “开启代理”，若开启了，检查代理地址是否正确，并重启应用

**Comment by bilibili-ayang** [comment]
@nihaozyj openai 只支持最大 4096 token 长度，你的 token 长度都到 5302 了，所以这个报错是 token 超出，需要新建对话！

**Comment by nihaozyj** [comment]
关掉记忆模式之后，可以正常使用了。 但是开启记忆模式之后，由于上次对话太长会导致token长度过大，应该怎么解决呢？

**Comment by nihaozyj** [comment]
@bilibili-ayang @DongHuiTiao 关掉记忆模式之后，可以正常使用了。 但是开启记忆模式之后，由于上次对话太长会导致token长度过大，应该怎么解决呢？

**Comment by nihaozyj** [comment]
![image](https://user-images.githubusercontent.com/58590015/230702078-08546a29-1efc-4139-b0e3-88a061f62875.png)

**Comment by bilibili-ayang** [comment]
> @bilibili-ayang @DongHuiTiao 关掉记忆模式之后，可以正常使用了。 但是开启记忆模式之后，由于上次对话太长会导致token长度过大，应该怎么解决呢？

暂时没有办法，这是openai的限制，我们也无能为力呀！
