### ISSUE TITLE
Survey for feature [Resize Window]（调查: 是否增加窗口调整大小的功能）

### ISSUE THREAD

**Issue by orangelckc** [Synaptrix/ChatGPT-Desktop#198]
很多的用户反馈，希望增加窗口大小调整的功能，我们在这里做一下调查。

请在对应的评论中点击表情，表示您的选择。

感谢您的支持～

As many users have provided feedback requesting the addition of a window resizing function, we are conducting a survey here. 

Please click on the emoji in the corresponding comment to indicate your preference.

Thanks for your support.

**Comment by orangelckc** [comment]
我需要调整窗口大小的功能

I need this feature.

**Comment by orangelckc** [comment]
对我没有什么影响，我没有这个需求

It's OK for me now.

**Comment by lethelong** [comment]
我个人认为需要调整窗口大小的功能，这样设计更符合Windows用户习惯

**Comment by Nihilitior** [comment]
需要，偶尔需要调整窗口，便于显示

**Comment by 1801256646** [comment]
虽然我不用，但是我觉得需要😄

**Comment by laohuan12138** [comment]
确实需要

**Comment by RanxinStart** [comment]
我认为需要的，自动的窗口在两块不同分辨率的屏幕下不能来回兼容。。
左屏幕1k 右屏幕2K曲面，导致打开时窗口过大 无法在1k屏幕下显示了(装不下)。

**Comment by ayangweb** [comment]
- #224
