### ISSUE TITLE
21款mac pro 无法移动窗口，关闭应用

### ISSUE THREAD

**Issue by wgsed** [Synaptrix/ChatGPT-Desktop#204]
我使用的是21款的MacBook Pro  ，我打开应用以后，无法移动，无法关闭，而且在屏幕上方的菜单栏，显示的是其他应用的菜单，只能通过活动监视器才能强制关闭

**Comment by wgsed** [comment]
我的电脑版本是13.2.1

**Comment by bilibili-ayang** [comment]
#172 

退出应用在托盘菜单中
