### ISSUE TITLE
希望在markdown渲染中增加对公式的支持

### ISSUE THREAD

**Issue by ocean0117** [Synaptrix/ChatGPT-Desktop#212]
如题：
![image](https://user-images.githubusercontent.com/51983215/232952501-da663923-8210-4e5d-bf07-3dbfa9f867ad.png)
虽然chatgpt数学能力孱弱，但给出一些常见的公式定理还是靠谱的，所以希望支持这个功能。

**Comment by orangelckc** [comment]
已添加对latex公式渲染支持
![ChatGPT-Desktop-1681901164530](https://user-images.githubusercontent.com/48410934/233052415-54f1e5b6-40f9-46e6-865b-1578d3d64521.png)
