### ISSUE TITLE
为啥有会话就不让删呢？

### ISSUE THREAD

**Issue by lhj5426** [Synaptrix/ChatGPT-Desktop#213]
![image](https://user-images.githubusercontent.com/30548000/232955764-dc7a75d3-5bf7-4f74-bdc5-691416163358.png)

用过很多 有没有会话 都是想删就删？ 这个不让删 只能一直创建新的 结果创建了一堆。。 
这很不合理吧

**Comment by bilibili-ayang** [comment]
因为我们采用了物理删除，历史会话和角色信息是多表查询的，如果直接删除角色，历史会话找不到角色信息就会报错，不过你这样也算是给我提了个醒，我们完全可以采用逻辑删除
