### ISSUE TITLE
[问题]会话记录里没有正确显示机器人的名字，显示为{name}

### ISSUE THREAD

**Issue by xindoo** [Synaptrix/ChatGPT-Desktop#227]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/3211189/236076648-5d94fe9f-4749-4636-a4ea-488885f087b7.png">

**Comment by ayangweb** [comment]
感谢反馈，我们这边修复一下

**Comment by ayangweb** [comment]
1.0.3 已经解决此问题，更新即可！
